CREATE USER 'CarCoversAdmin'@'localhost' IDENTIFIED BY 'X4mv0nkQlVcoWmPo';
GRANT ALL PRIVILEGES ON *.* TO 'CarCoversAdmin'@'localhost' REQUIRE SSL WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
