#!/usr/bin/env node

var program = require('commander');

program
	.version('0.0.1');

program
	.command('update')
	.description('Update the custom_covers table with DCI files')
	.option('-f, --file <file>', 'Path to CSV file with updates (relative to cwd)')
	.option('--verbose', 'Run script in verbose mode')
	.action(function(cmd, options) {
		require('./cli/update')(cmd, options);
	});

if (!process.argv.slice(2).length) {
	program.outputHelp();
}

program.parse(process.argv);
