-- MySQL dump 10.13  Distrib 5.6.22, for osx10.8 (x86_64)
--
-- Host: localhost    Database: tjcars
-- ------------------------------------------------------
-- Server version	5.6.22

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `cfccprices`
--

DROP TABLE IF EXISTS `cfccprices`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `cfccprices` (
  `name` varchar(255) DEFAULT NULL,
  `abrv` varchar(255) DEFAULT NULL,
  `colors` varchar(255) DEFAULT NULL,
  `hasMultipleColors` tinyint(1) NOT NULL DEFAULT '0',
  `ext` varchar(255) DEFAULT NULL,
  `size` enum('G1','G2','G3','G4','G5','G6','T0','T1','T2','T3','T4','T5') DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `warranty` varchar(255) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  `section` varchar(255) DEFAULT NULL,
  `retail` varchar(255) DEFAULT NULL,
  `jobber` varchar(255) DEFAULT NULL,
  `weight` double DEFAULT NULL,
  `length` double DEFAULT NULL,
  `width` double DEFAULT NULL,
  `height` double DEFAULT NULL,
  `rushManufacture` tinyint(1) DEFAULT '1',
  `isMultiColor` tinyint(1) DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `cfccprices`
--

LOCK TABLES `cfccprices` WRITE;
/*!40000 ALTER TABLE `cfccprices` DISABLE KEYS */;
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Technalon','evo','Gray.Tan',1,'GK.TK','G1','Highly Popular All-Weather Fabric. Dent Protecting 4-Layer Construction. Water & Dust Resistant. Strong Polypropylene Fibers. Insulates Vehicle Against Weather. Great Protection at an Affordable Price. 4 Years Warranty.','4 Years','Outdoor/Indoor','evolution.php','256.95','164.09',8,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Technalon','evo','Gray.Tan',1,'GK.TK','G2','Highly Popular All-Weather Fabric. Dent Protecting 4-Layer Construction. Water & Dust Resistant. Strong Polypropylene Fibers. Insulates Vehicle Against Weather. Great Protection at an Affordable Price. 4 Years Warranty.','4 Years','Outdoor/Indoor','evolution.php','285.50','182.32',9,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Technalon','evo','Gray.Tan',1,'GK.TK','G3','Highly Popular All-Weather Fabric. Dent Protecting 4-Layer Construction. Water & Dust Resistant. Strong Polypropylene Fibers. Insulates Vehicle Against Weather. Great Protection at an Affordable Price. 4 Years Warranty.','4 Years','Outdoor/Indoor','evolution.php','323.56','206.63',9,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Technalon','evo','Gray.Tan',1,'GK.TK','G4','Highly Popular All-Weather Fabric. Dent Protecting 4-Layer Construction. Water & Dust Resistant. Strong Polypropylene Fibers. Insulates Vehicle Against Weather. Great Protection at an Affordable Price. 4 Years Warranty.','4 Years','Outdoor/Indoor','evolution.php','391.79','250.20',14,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Technalon','evo','Gray.Tan',1,'GK.TK','G5','Highly Popular All-Weather Fabric. Dent Protecting 4-Layer Construction. Water & Dust Resistant. Strong Polypropylene Fibers. Insulates Vehicle Against Weather. Great Protection at an Affordable Price. 4 Years Warranty.','4 Years','Outdoor/Indoor','evolution.php','445.73','284.64',14,12,12,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Technalon','evo','Gray.Tan',1,'GK.TK','G6','Highly Popular All-Weather Fabric. Dent Protecting 4-Layer Construction. Water & Dust Resistant. Strong Polypropylene Fibers. Insulates Vehicle Against Weather. Great Protection at an Affordable Price. 4 Years Warranty.','4 Years','Outdoor/Indoor','evolution.php','560.53','357.96',16,12,12,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Technalon','evo','Gray.Tan',1,'GK.TK','T0','Highly Popular All-Weather Fabric. Dent Protecting 4-Layer Construction. Water & Dust Resistant. Strong Polypropylene Fibers. Insulates Vehicle Against Weather. Great Protection at an Affordable Price. 4 Years Warranty.','4 Years','Outdoor/Indoor','evolution.php','299.95','191.55',7,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Technalon','evo','Gray.Tan',1,'GK.TK','T1','Highly Popular All-Weather Fabric. Dent Protecting 4-Layer Construction. Water & Dust Resistant. Strong Polypropylene Fibers. Insulates Vehicle Against Weather. Great Protection at an Affordable Price. 4 Years Warranty.','4 Years','Outdoor/Indoor','evolution.php','338.48','216.16',14,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Technalon','evo','Gray.Tan',1,'GK.TK','T2','Highly Popular All-Weather Fabric. Dent Protecting 4-Layer Construction. Water & Dust Resistant. Strong Polypropylene Fibers. Insulates Vehicle Against Weather. Great Protection at an Affordable Price. 4 Years Warranty.','4 Years','Outdoor/Indoor','evolution.php','406.68','259.70',14,12,12,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Technalon','evo','Gray.Tan',1,'GK.TK','T3','Highly Popular All-Weather Fabric. Dent Protecting 4-Layer Construction. Water & Dust Resistant. Strong Polypropylene Fibers. Insulates Vehicle Against Weather. Great Protection at an Affordable Price. 4 Years Warranty.','4 Years','Outdoor/Indoor','evolution.php','460.65','294.17',17,12,12,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Technalon','evo','Gray.Tan',1,'GK.TK','T4','Highly Popular All-Weather Fabric. Dent Protecting 4-Layer Construction. Water & Dust Resistant. Strong Polypropylene Fibers. Insulates Vehicle Against Weather. Great Protection at an Affordable Price. 4 Years Warranty.','4 Years','Outdoor/Indoor','evolution.php','574.98','367.18',NULL,12,12,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Technalon','evo','Gray.Tan',1,'GK.TK','T5','Highly Popular All-Weather Fabric. Dent Protecting 4-Layer Construction. Water & Dust Resistant. Strong Polypropylene Fibers. Insulates Vehicle Against Weather. Great Protection at an Affordable Price. 4 Years Warranty.','4 Years','Outdoor/Indoor','evolution.php','638.27','407.60',NULL,12,12,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Sunbrella','sun','Pacific Blue.Cadet Gray.Toast',1,'D1.D4.D6','G1','Durable Long-Lasting Fabric. Best For Intense Sun Locations. Solution Dyed Woven Acrylic. Provides Almost Complete UV Block, protecting Interior and Exterior Finish. 5 Year Warranty.','5 Years','Outdoor/Indoor','sunbrella.php','564.31','360.37',10,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Sunbrella','sun','Pacific Blue.Cadet Gray.Toast',1,'D1.D4.D6','G2','Durable Long-Lasting Fabric. Best For Intense Sun Locations. Solution Dyed Woven Acrylic. Provides Almost Complete UV Block, protecting Interior and Exterior Finish. 5 Year Warranty.','5 Years','Outdoor/Indoor','sunbrella.php','626.98','400.39',12,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Sunbrella','sun','Pacific Blue.Cadet Gray.Toast',1,'D1.D4.D6','G3','Durable Long-Lasting Fabric. Best For Intense Sun Locations. Solution Dyed Woven Acrylic. Provides Almost Complete UV Block, protecting Interior and Exterior Finish. 5 Year Warranty.','5 Years','Outdoor/Indoor','sunbrella.php','710.05','453.44',12,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Sunbrella','sun','Pacific Blue.Cadet Gray.Toast',1,'D1.D4.D6','G4','Durable Long-Lasting Fabric. Best For Intense Sun Locations. Solution Dyed Woven Acrylic. Provides Almost Complete UV Block, protecting Interior and Exterior Finish. 5 Year Warranty.','5 Years','Outdoor/Indoor','sunbrella.php','791.40','505.39',18,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Sunbrella','sun','Pacific Blue.Cadet Gray.Toast',1,'D1.D4.D6','G5','Durable Long-Lasting Fabric. Best For Intense Sun Locations. Solution Dyed Woven Acrylic. Provides Almost Complete UV Block, protecting Interior and Exterior Finish. 5 Year Warranty.','5 Years','Outdoor/Indoor','sunbrella.php','977.82','624.44',18,12,12,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Sunbrella','sun','Pacific Blue.Cadet Gray.Toast',1,'D1.D4.D6','G6','Durable Long-Lasting Fabric. Best For Intense Sun Locations. Solution Dyed Woven Acrylic. Provides Almost Complete UV Block, protecting Interior and Exterior Finish. 5 Year Warranty.','5 Years','Outdoor/Indoor','sunbrella.php','1216.60','776.92',20,12,12,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Sunbrella','sun','Pacific Blue.Cadet Gray.Toast',1,'D1.D4.D6','T0','Durable Long-Lasting Fabric. Best For Intense Sun Locations. Solution Dyed Woven Acrylic. Provides Almost Complete UV Block, protecting Interior and Exterior Finish. 5 Year Warranty.','5 Years','Outdoor/Indoor','sunbrella.php','642.58','410.35',10,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Sunbrella','sun','Pacific Blue.Cadet Gray.Toast',1,'D1.D4.D6','T1','Durable Long-Lasting Fabric. Best For Intense Sun Locations. Solution Dyed Woven Acrylic. Provides Almost Complete UV Block, protecting Interior and Exterior Finish. 5 Year Warranty.','5 Years','Outdoor/Indoor','sunbrella.php','725.98','463.61',18,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Sunbrella','sun','Pacific Blue.Cadet Gray.Toast',1,'D1.D4.D6','T2','Durable Long-Lasting Fabric. Best For Intense Sun Locations. Solution Dyed Woven Acrylic. Provides Almost Complete UV Block, protecting Interior and Exterior Finish. 5 Year Warranty.','5 Years','Outdoor/Indoor','sunbrella.php','807.34','515.57',18,12,12,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Sunbrella','sun','Pacific Blue.Cadet Gray.Toast',1,'D1.D4.D6','T3','Durable Long-Lasting Fabric. Best For Intense Sun Locations. Solution Dyed Woven Acrylic. Provides Almost Complete UV Block, protecting Interior and Exterior Finish. 5 Year Warranty.','5 Years','Outdoor/Indoor','sunbrella.php','993.74','634.60',22,12,12,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Sunbrella','sun','Pacific Blue.Cadet Gray.Toast',1,'D1.D4.D6','T4','Durable Long-Lasting Fabric. Best For Intense Sun Locations. Solution Dyed Woven Acrylic. Provides Almost Complete UV Block, protecting Interior and Exterior Finish. 5 Year Warranty.','5 Years','Outdoor/Indoor','sunbrella.php','1232.23','786.90',NULL,12,12,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Sunbrella','sun','Pacific Blue.Cadet Gray.Toast',1,'D1.D4.D6','T5','Durable Long-Lasting Fabric. Best For Intense Sun Locations. Solution Dyed Woven Acrylic. Provides Almost Complete UV Block, protecting Interior and Exterior Finish. 5 Year Warranty.','5 Years','Outdoor/Indoor','sunbrella.php','1367.76','873.45',NULL,12,12,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Noah','nh','Gray',0,'NH','G1','All-Weather Protection utilizing Film Barrier Technology. This non-woven fabric is a high-tech, Bonded 4-Layer Composite, providing Multi-Layer Protection for your car\'s finish. Kimberly-Clark\'s Best Outdoor Fabric. 4 Year Warranty.','4 Years','Outdoor/Indoor','noah.php','298.40','190.56',7,6.5,6.5,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Noah','nh','Gray',0,'NH','G2','All-Weather Protection utilizing Film Barrier Technology. This non-woven fabric is a high-tech, Bonded 4-Layer Composite, providing Multi-Layer Protection for your car\'s finish. Kimberly-Clark\'s Best Outdoor Fabric. 4 Year Warranty.','4 Years','Outdoor/Indoor','noah.php','334.03','213.31',8,6.5,6.5,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Noah','nh','Gray',0,'NH','G3','All-Weather Protection utilizing Film Barrier Technology. This non-woven fabric is a high-tech, Bonded 4-Layer Composite, providing Multi-Layer Protection for your car\'s finish. Kimberly-Clark\'s Best Outdoor Fabric. 4 Year Warranty.','4 Years','Outdoor/Indoor','noah.php','375.44','239.75',8,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Noah','nh','Gray',0,'NH','G4','All-Weather Protection utilizing Film Barrier Technology. This non-woven fabric is a high-tech, Bonded 4-Layer Composite, providing Multi-Layer Protection for your car\'s finish. Kimberly-Clark\'s Best Outdoor Fabric. 4 Year Warranty.','4 Years','Outdoor/Indoor','noah.php','444.15','283.63',12,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Noah','nh','Gray',0,'NH','G5','All-Weather Protection utilizing Film Barrier Technology. This non-woven fabric is a high-tech, Bonded 4-Layer Composite, providing Multi-Layer Protection for your car\'s finish. Kimberly-Clark\'s Best Outdoor Fabric. 4 Year Warranty.','4 Years','Outdoor/Indoor','noah.php','549.45','350.88',13,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Noah','nh','Gray',0,'NH','G6','All-Weather Protection utilizing Film Barrier Technology. This non-woven fabric is a high-tech, Bonded 4-Layer Composite, providing Multi-Layer Protection for your car\'s finish. Kimberly-Clark\'s Best Outdoor Fabric. 4 Year Warranty.','4 Years','Outdoor/Indoor','noah.php','628.87','401.60',15,12,12,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Noah','nh','Gray',0,'NH','T0','All-Weather Protection utilizing Film Barrier Technology. This non-woven fabric is a high-tech, Bonded 4-Layer Composite, providing Multi-Layer Protection for your car\'s finish. Kimberly-Clark\'s Best Outdoor Fabric. 4 Year Warranty.','4 Years','Outdoor/Indoor','noah.php','348.69','222.68',7,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Noah','nh','Gray',0,'NH','T1','All-Weather Protection utilizing Film Barrier Technology. This non-woven fabric is a high-tech, Bonded 4-Layer Composite, providing Multi-Layer Protection for your car\'s finish. Kimberly-Clark\'s Best Outdoor Fabric. 4 Year Warranty.','4 Years','Outdoor/Indoor','noah.php','398.71','254.62',13,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Noah','nh','Gray',0,'NH','T2','All-Weather Protection utilizing Film Barrier Technology. This non-woven fabric is a high-tech, Bonded 4-Layer Composite, providing Multi-Layer Protection for your car\'s finish. Kimberly-Clark\'s Best Outdoor Fabric. 4 Year Warranty.','4 Years','Outdoor/Indoor','noah.php','467.69','298.67',13,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Noah','nh','Gray',0,'NH','T3','All-Weather Protection utilizing Film Barrier Technology. This non-woven fabric is a high-tech, Bonded 4-Layer Composite, providing Multi-Layer Protection for your car\'s finish. Kimberly-Clark\'s Best Outdoor Fabric. 4 Year Warranty.','4 Years','Outdoor/Indoor','noah.php','551.52','352.20',15,12,12,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Noah','nh','Gray',0,'NH','T4','All-Weather Protection utilizing Film Barrier Technology. This non-woven fabric is a high-tech, Bonded 4-Layer Composite, providing Multi-Layer Protection for your car\'s finish. Kimberly-Clark\'s Best Outdoor Fabric. 4 Year Warranty.','4 Years','Outdoor/Indoor','noah.php','661.92','422.70',NULL,12,12,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Noah','nh','Gray',0,'NH','T5','All-Weather Protection utilizing Film Barrier Technology. This non-woven fabric is a high-tech, Bonded 4-Layer Composite, providing Multi-Layer Protection for your car\'s finish. Kimberly-Clark\'s Best Outdoor Fabric. 4 Year Warranty.','4 Years','Outdoor/Indoor','noah.php','742.40','474.10',NULL,12,12,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('WeatherShield HD','wsHD','Gray',0,'HG','G1','&quot;Outsmart the Outdoors&quot; with this Heavy-Duty Version of Weathershield with Nextec&reg; Barrier Finish by Epic. Weathershield HD Sheds Water, Blocks Dust/Dirt, & Still Breathes! Solution Dyed Fibers Resist Fade. 5 Year Warranty.','5 Years','Outdoor/Indoor','weathershieldHD.php','524.84','344.92',10,6.5,6.5,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('WeatherShield HD','wsHD','Gray',0,'HG','G2','&quot;Outsmart the Outdoors&quot; with this Heavy-Duty Version of Weathershield with Nextec&reg; Barrier Finish by Epic. Weathershield HD Sheds Water, Blocks Dust/Dirt, & Still Breathes! Solution Dyed Fibers Resist Fade. 5 Year Warranty.','5 Years','Outdoor/Indoor','weathershieldHD.php','590.24','387.91',12,6.5,6.5,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('WeatherShield HD','wsHD','Gray',0,'HG','G3','&quot;Outsmart the Outdoors&quot; with this Heavy-Duty Version of Weathershield with Nextec&reg; Barrier Finish by Epic. Weathershield HD Sheds Water, Blocks Dust/Dirt, & Still Breathes! Solution Dyed Fibers Resist Fade. 5 Year Warranty.','5 Years','Outdoor/Indoor','weathershieldHD.php','680.75','447.39',14,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('WeatherShield HD','wsHD','Gray',0,'HG','G4','&quot;Outsmart the Outdoors&quot; with this Heavy-Duty Version of Weathershield with Nextec&reg; Barrier Finish by Epic. Weathershield HD Sheds Water, Blocks Dust/Dirt, & Still Breathes! Solution Dyed Fibers Resist Fade. 5 Year Warranty.','5 Years','Outdoor/Indoor','weathershieldHD.php','827.32','543.72',18,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('WeatherShield HD','wsHD','Gray',0,'HG','G5','&quot;Outsmart the Outdoors&quot; with this Heavy-Duty Version of Weathershield with Nextec&reg; Barrier Finish by Epic. Weathershield HD Sheds Water, Blocks Dust/Dirt, & Still Breathes! Solution Dyed Fibers Resist Fade. 5 Year Warranty.','5 Years','Outdoor/Indoor','weathershieldHD.php','1003.18','659.29',18,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('WeatherShield HD','wsHD','Gray',0,'HG','G6','&quot;Outsmart the Outdoors&quot; with this Heavy-Duty Version of Weathershield with Nextec&reg; Barrier Finish by Epic. Weathershield HD Sheds Water, Blocks Dust/Dirt, & Still Breathes! Solution Dyed Fibers Resist Fade. 5 Year Warranty.','5 Years','Outdoor/Indoor','weathershieldHD.php','1237.19','813.08',20,12,12,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('WeatherShield HD','wsHD','Gray',0,'HG','T0','&quot;Outsmart the Outdoors&quot; with this Heavy-Duty Version of Weathershield with Nextec&reg; Barrier Finish by Epic. Weathershield HD Sheds Water, Blocks Dust/Dirt, & Still Breathes! Solution Dyed Fibers Resist Fade. 5 Year Warranty.','5 Years','Outdoor/Indoor','weathershieldHD.php','584.34','384.03',10,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('WeatherShield HD','wsHD','Gray',0,'HG','T1','&quot;Outsmart the Outdoors&quot; with this Heavy-Duty Version of Weathershield with Nextec&reg; Barrier Finish by Epic. Weathershield HD Sheds Water, Blocks Dust/Dirt, & Still Breathes! Solution Dyed Fibers Resist Fade. 5 Year Warranty.','5 Years','Outdoor/Indoor','weathershieldHD.php','727.19','477.91',18,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('WeatherShield HD','wsHD','Gray',0,'HG','T2','&quot;Outsmart the Outdoors&quot; with this Heavy-Duty Version of Weathershield with Nextec&reg; Barrier Finish by Epic. Weathershield HD Sheds Water, Blocks Dust/Dirt, & Still Breathes! Solution Dyed Fibers Resist Fade. 5 Year Warranty.','5 Years','Outdoor/Indoor','weathershieldHD.php','858.48','564.20',18,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('WeatherShield HD','wsHD','Gray',0,'HG','T3','&quot;Outsmart the Outdoors&quot; with this Heavy-Duty Version of Weathershield with Nextec&reg; Barrier Finish by Epic. Weathershield HD Sheds Water, Blocks Dust/Dirt, & Still Breathes! Solution Dyed Fibers Resist Fade. 5 Year Warranty.','5 Years','Outdoor/Indoor','weathershieldHD.php','1018.34','669.25',22,12,12,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('WeatherShield HD','wsHD','Gray',0,'HG','T4','&quot;Outsmart the Outdoors&quot; with this Heavy-Duty Version of Weathershield with Nextec&reg; Barrier Finish by Epic. Weathershield HD Sheds Water, Blocks Dust/Dirt, & Still Breathes! Solution Dyed Fibers Resist Fade. 5 Year Warranty.','5 Years','Outdoor/Indoor','weathershieldHD.php','1223.10','803.82',NULL,12,12,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('WeatherShield HD','wsHD','Gray',0,'HG','T5','&quot;Outsmart the Outdoors&quot; with this Heavy-Duty Version of Weathershield with Nextec&reg; Barrier Finish by Epic. Weathershield HD Sheds Water, Blocks Dust/Dirt, & Still Breathes! Solution Dyed Fibers Resist Fade. 5 Year Warranty.','5 Years','Outdoor/Indoor','weathershieldHD.php','1385.58','910.60',NULL,12,12,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('WeatherShield HP','wsHP','Gray.Taupe.Yellow.Bright Blue.Light Blue.Green.Red.Black',1,'PG.PT.PY.PA.PL.PN.PR.PB','G1','Ultimate all-weather fabric. Dramatic Rain Dispersion / Superior Dry Time & Breathablility. Solution-dyed fibers are UV & Fade Resistant. Light-Weight/Packs Small / Easy Care. 4 Year Warranty.','4 Years','Outdoor/Indoor','weathershield.php','395.91;395.91;439.67;439.67;439.67;439.67;439.67;439.67','252.83;252.83;280.78;280.78;280.78;280.78;280.78;280.78',8,6.5,6.5,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('WeatherShield HP','wsHP','Gray.Taupe.Yellow.Bright Blue.Light Blue.Green.Red.Black',1,'PG.PT.PY.PA.PL.PN.PR.PB','G2','Ultimate all-weather fabric. Dramatic Rain Dispersion / Superior Dry Time & Breathablility. Solution-dyed fibers are UV & Fade Resistant. Light-Weight/Packs Small / Easy Care. 4 Year Warranty.','4 Years','Outdoor/Indoor','weathershield.php','449.29;449.29;500.37;500.37;500.37;500.37;500.37;500.37','286.92;286.92;319.54;319.54;319.54;319.54;319.54;319.54',9,6.5,6.5,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('WeatherShield HP','wsHP','Gray.Taupe.Yellow.Bright Blue.Light Blue.Green.Red.Black',1,'PG.PT.PY.PA.PL.PN.PR.PB','G3','Ultimate all-weather fabric. Dramatic Rain Dispersion / Superior Dry Time & Breathablility. Solution-dyed fibers are UV & Fade Resistant. Light-Weight/Packs Small / Easy Care. 4 Year Warranty.','4 Years','Outdoor/Indoor','weathershield.php','512.82;512.82;573.58;573.58;573.58;573.58;573.58;573.58','327.49;327.49;366.29;366.29;366.29;366.29;366.29;366.29',9,6.5,6.5,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('WeatherShield HP','wsHP','Gray.Taupe.Yellow.Bright Blue.Light Blue.Green.Red.Black',1,'PG.PT.PY.PA.PL.PN.PR.PB','G4','Ultimate all-weather fabric. Dramatic Rain Dispersion / Superior Dry Time & Breathablility. Solution-dyed fibers are UV & Fade Resistant. Light-Weight/Packs Small / Easy Care. 4 Year Warranty.','4 Years','Outdoor/Indoor','weathershield.php','619.64;619.64;696.61;696.61;696.61;696.61;696.61;696.61','395.71;395.71;444.86;444.86;444.86;444.86;444.86;444.86',14,6.5,6.5,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('WeatherShield HP','wsHP','Gray.Taupe.Yellow.Bright Blue.Light Blue.Green.Red.Black',1,'PG.PT.PY.PA.PL.PN.PR.PB','G5','Ultimate all-weather fabric. Dramatic Rain Dispersion / Superior Dry Time & Breathablility. Solution-dyed fibers are UV & Fade Resistant. Light-Weight/Packs Small / Easy Care. 4 Year Warranty.','4 Years','Outdoor/Indoor','weathershield.php','731.9;731.9;832.4;832.4;832.4;832.4;832.4;832.4','467.39;467.39;531.57;531.57;531.57;531.57;531.57;531.57',14,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('WeatherShield HP','wsHP','Gray.Taupe.Yellow.Bright Blue.Light Blue.Green.Red.Black',1,'PG.PT.PY.PA.PL.PN.PR.PB','G6','Ultimate all-weather fabric. Dramatic Rain Dispersion / Superior Dry Time & Breathablility. Solution-dyed fibers are UV & Fade Resistant. Light-Weight/Packs Small / Easy Care. 4 Year Warranty.','4 Years','Outdoor/Indoor','weathershield.php','910.9;910.9;1032.88;1032.88;1032.88;1032.88;1032.88;1032.88','581.70;581.70;659.60;659.60;659.60;659.60;659.60;659.60',16,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('WeatherShield HP','wsHP','Gray.Taupe.Yellow.Bright Blue.Light Blue.Green.Red.Black',1,'PG.PT.PY.PA.PL.PN.PR.PB','T0','Ultimate all-weather fabric. Dramatic Rain Dispersion / Superior Dry Time & Breathablility. Solution-dyed fibers are UV & Fade Resistant. Light-Weight/Packs Small / Easy Care. 4 Year Warranty.','4 Years','Outdoor/Indoor','weathershield.php','464.53;464.53;515.7;515.7;515.7;515.7;515.7;515.7','296.65;296.65;329.33;329.33;329.33;329.33;329.33;329.33',8,6.5,6.5,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('WeatherShield HP','wsHP','Gray.Taupe.Yellow.Bright Blue.Light Blue.Green.Red.Black',1,'PG.PT.PY.PA.PL.PN.PR.PB','T1','Ultimate all-weather fabric. Dramatic Rain Dispersion / Superior Dry Time & Breathablility. Solution-dyed fibers are UV & Fade Resistant. Light-Weight/Packs Small / Easy Care. 4 Year Warranty.','4 Years','Outdoor/Indoor','weathershield.php','543.54;543.54;609.08;609.08;609.08;609.08;609.08;609.08','347.11;347.11;388.96;388.96;388.96;388.96;388.96;388.96',14,6.5,6.5,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('WeatherShield HP','wsHP','Gray.Taupe.Yellow.Bright Blue.Light Blue.Green.Red.Black',1,'PG.PT.PY.PA.PL.PN.PR.PB','T2','Ultimate all-weather fabric. Dramatic Rain Dispersion / Superior Dry Time & Breathablility. Solution-dyed fibers are UV & Fade Resistant. Light-Weight/Packs Small / Easy Care. 4 Year Warranty.','4 Years','Outdoor/Indoor','weathershield.php','642.14;642.14;722.53;722.53;722.53;722.53;722.53;722.53','410.07;410.07;461.41;461.41;461.41;461.41;461.41;461.41',16,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('WeatherShield HP','wsHP','Gray.Taupe.Yellow.Bright Blue.Light Blue.Green.Red.Black',1,'PG.PT.PY.PA.PL.PN.PR.PB','T3','Ultimate all-weather fabric. Dramatic Rain Dispersion / Superior Dry Time & Breathablility. Solution-dyed fibers are UV & Fade Resistant. Light-Weight/Packs Small / Easy Care. 4 Year Warranty.','4 Years','Outdoor/Indoor','weathershield.php','756.14;756.14;854.12;854.12;854.12;854.12;854.12;854.12','482.87;482.87;545.45;545.45;545.45;545.45;545.45;545.45',15,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('WeatherShield HP','wsHP','Gray.Taupe.Yellow.Bright Blue.Light Blue.Green.Red.Black',1,'PG.PT.PY.PA.PL.PN.PR.PB','T4','Ultimate all-weather fabric. Dramatic Rain Dispersion / Superior Dry Time & Breathablility. Solution-dyed fibers are UV & Fade Resistant. Light-Weight/Packs Small / Easy Care. 4 Year Warranty.','4 Years','Outdoor/Indoor','weathershield.php','924.69;924.69;1048.41;1048.41;1048.41;1048.41;1048.41;1048.41','590.51;590.51;669.52;669.52;669.52;669.52;669.52;669.52',NULL,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('WeatherShield HP','wsHP','Gray.Taupe.Yellow.Bright Blue.Light Blue.Green.Red.Black',1,'PG.PT.PY.PA.PL.PN.PR.PB','T5','Ultimate all-weather fabric. Dramatic Rain Dispersion / Superior Dry Time & Breathablility. Solution-dyed fibers are UV & Fade Resistant. Light-Weight/Packs Small / Easy Care. 4 Year Warranty.','4 Years','Outdoor/Indoor','weathershield.php','1039.33;1039.33;1181.12;1181.12;1181.12;1181.12;1181.12;1181.12','663.72;663.72;754.27;754.27;754.27;754.27;754.27;754.27',NULL,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('WeatherShield MultiColor','wsMC','MultiColor',0,'PX','G1','Ultimate all-weather fabric styled in 2 colors choices. Dramatic Rain Dispersion / Superior Dry Time & Breathablility. Solution-dyed fibers are UV & Fade Resistant. Light-Weight/Packs Small / Easy Care. 4 Year Warranty.','4 Years','Outdoor/Indoor','weathershield.php','491.23','313.70',8,6.5,6.5,24,0,1);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('WeatherShield MultiColor','wsMC','MultiColor',0,'PX','G2','Ultimate all-weather fabric styled in 2 colors choices. Dramatic Rain Dispersion / Superior Dry Time & Breathablility. Solution-dyed fibers are UV & Fade Resistant. Light-Weight/Packs Small / Easy Care. 4 Year Warranty.','4 Years','Outdoor/Indoor','weathershield.php','559.02','356.99',9,6.5,6.5,24,0,1);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('WeatherShield MultiColor','wsMC','MultiColor',0,'PX','G3','Ultimate all-weather fabric styled in 2 colors choices. Dramatic Rain Dispersion / Superior Dry Time & Breathablility. Solution-dyed fibers are UV & Fade Resistant. Light-Weight/Packs Small / Easy Care. 4 Year Warranty.','4 Years','Outdoor/Indoor','weathershield.php','640.82','409.23',9,6.5,6.5,24,0,1);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('WeatherShield MultiColor','wsMC','MultiColor',0,'PX','G4','Ultimate all-weather fabric styled in 2 colors choices. Dramatic Rain Dispersion / Superior Dry Time & Breathablility. Solution-dyed fibers are UV & Fade Resistant. Light-Weight/Packs Small / Easy Care. 4 Year Warranty.','4 Years','Outdoor/Indoor','weathershield.php','778.24','496.99',14,6.5,6.5,24,0,1);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('WeatherShield MultiColor','wsMC','MultiColor',0,'PX','G5','Ultimate all-weather fabric styled in 2 colors choices. Dramatic Rain Dispersion / Superior Dry Time & Breathablility. Solution-dyed fibers are UV & Fade Resistant. Light-Weight/Packs Small / Easy Care. 4 Year Warranty.','4 Years','Outdoor/Indoor','weathershield.php','929.94','593.86',14,9,9,24,0,1);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('WeatherShield MultiColor','wsMC','MultiColor',0,'PX','G6','Ultimate all-weather fabric styled in 2 colors choices. Dramatic Rain Dispersion / Superior Dry Time & Breathablility. Solution-dyed fibers are UV & Fade Resistant. Light-Weight/Packs Small / Easy Care. 4 Year Warranty.','4 Years','Outdoor/Indoor','weathershield.php','1153.94','736.90',16,9,9,24,0,1);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('WeatherShield MultiColor','wsMC','MultiColor',0,'PX','T0','Ultimate all-weather fabric styled in 2 colors choices. Dramatic Rain Dispersion / Superior Dry Time & Breathablility. Solution-dyed fibers are UV & Fade Resistant. Light-Weight/Packs Small / Easy Care. 4 Year Warranty.','4 Years','Outdoor/Indoor','weathershield.php','576.13','367.92',8,6.5,6.5,24,0,1);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('WeatherShield MultiColor','wsMC','MultiColor',0,'PX','T1','Ultimate all-weather fabric styled in 2 colors choices. Dramatic Rain Dispersion / Superior Dry Time & Breathablility. Solution-dyed fibers are UV & Fade Resistant. Light-Weight/Packs Small / Easy Care. 4 Year Warranty.','4 Years','Outdoor/Indoor','weathershield.php','680.47','434.55',14,6.5,6.5,24,0,1);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('WeatherShield MultiColor','wsMC','MultiColor',0,'PX','T2','Ultimate all-weather fabric styled in 2 colors choices. Dramatic Rain Dispersion / Superior Dry Time & Breathablility. Solution-dyed fibers are UV & Fade Resistant. Light-Weight/Packs Small / Easy Care. 4 Year Warranty.','4 Years','Outdoor/Indoor','weathershield.php','806.85','515.26',16,9,9,24,0,1);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('WeatherShield MultiColor','wsMC','MultiColor',0,'PX','T3','Ultimate all-weather fabric styled in 2 colors choices. Dramatic Rain Dispersion / Superior Dry Time & Breathablility. Solution-dyed fibers are UV & Fade Resistant. Light-Weight/Packs Small / Easy Care. 4 Year Warranty.','4 Years','Outdoor/Indoor','weathershield.php','954.21','609.36',15,9,9,24,0,1);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('WeatherShield MultiColor','wsMC','MultiColor',0,'PX','T4','Ultimate all-weather fabric styled in 2 colors choices. Dramatic Rain Dispersion / Superior Dry Time & Breathablility. Solution-dyed fibers are UV & Fade Resistant. Light-Weight/Packs Small / Easy Care. 4 Year Warranty.','4 Years','Outdoor/Indoor','weathershield.php','1171.27','747.98',NULL,9,9,24,0,1);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('WeatherShield MultiColor','wsMC','MultiColor',0,'PX','T5','Ultimate all-weather fabric styled in 2 colors choices. Dramatic Rain Dispersion / Superior Dry Time & Breathablility. Solution-dyed fibers are UV & Fade Resistant. Light-Weight/Packs Small / Easy Care. 4 Year Warranty.','4 Years','Outdoor/Indoor','weathershield.php','1319.55','842.66',NULL,9,9,24,0,1);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Reflectect','rs','Gray',0,'RS','G1','Lightweight, Good All-Season Protection. Silver Urethane-Coated Polyester Fabric. Helps Keep the Vehicle Cooler. Water Resistant, Repels Dust and Dirt. Compact for Easy Trunk Storage. 3 Year Warranty.','3 Years','Outdoor/Indoor','reflectect.php','220.13','140.57',8,6.5,6.5,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Reflectect','rs','Gray',0,'RS','G2','Lightweight, Good All-Season Protection. Silver Urethane-Coated Polyester Fabric. Helps Keep the Vehicle Cooler. Water Resistant, Repels Dust and Dirt. Compact for Easy Trunk Storage. 3 Year Warranty.','3 Years','Outdoor/Indoor','reflectect.php','253.98','162.19',9,6.5,6.5,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Reflectect','rs','Gray',0,'RS','G3','Lightweight, Good All-Season Protection. Silver Urethane-Coated Polyester Fabric. Helps Keep the Vehicle Cooler. Water Resistant, Repels Dust and Dirt. Compact for Easy Trunk Storage. 3 Year Warranty.','3 Years','Outdoor/Indoor','reflectect.php','276.27','176.43',9,6.5,6.5,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Reflectect','rs','Gray',0,'RS','G4','Lightweight, Good All-Season Protection. Silver Urethane-Coated Polyester Fabric. Helps Keep the Vehicle Cooler. Water Resistant, Repels Dust and Dirt. Compact for Easy Trunk Storage. 3 Year Warranty.','3 Years','Outdoor/Indoor','reflectect.php','329.55','210.45',14,6.5,6.5,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Reflectect','rs','Gray',0,'RS','G5','Lightweight, Good All-Season Protection. Silver Urethane-Coated Polyester Fabric. Helps Keep the Vehicle Cooler. Water Resistant, Repels Dust and Dirt. Compact for Easy Trunk Storage. 3 Year Warranty.','3 Years','Outdoor/Indoor','reflectect.php','381.84','243.84',14,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Reflectect','rs','Gray',0,'RS','G6','Lightweight, Good All-Season Protection. Silver Urethane-Coated Polyester Fabric. Helps Keep the Vehicle Cooler. Water Resistant, Repels Dust and Dirt. Compact for Easy Trunk Storage. 3 Year Warranty.','3 Years','Outdoor/Indoor','reflectect.php','484.77','309.58',16,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Reflectect','rs','Gray',0,'RS','T0','Lightweight, Good All-Season Protection. Silver Urethane-Coated Polyester Fabric. Helps Keep the Vehicle Cooler. Water Resistant, Repels Dust and Dirt. Compact for Easy Trunk Storage. 3 Year Warranty.','3 Years','Outdoor/Indoor','reflectect.php','266.48','170.18',8,6.5,6.5,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Reflectect','rs','Gray',0,'RS','T1','Lightweight, Good All-Season Protection. Silver Urethane-Coated Polyester Fabric. Helps Keep the Vehicle Cooler. Water Resistant, Repels Dust and Dirt. Compact for Easy Trunk Storage. 3 Year Warranty.','3 Years','Outdoor/Indoor','reflectect.php','297.23','189.81',14,6.5,6.5,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Reflectect','rs','Gray',0,'RS','T2','Lightweight, Good All-Season Protection. Silver Urethane-Coated Polyester Fabric. Helps Keep the Vehicle Cooler. Water Resistant, Repels Dust and Dirt. Compact for Easy Trunk Storage. 3 Year Warranty.','3 Years','Outdoor/Indoor','reflectect.php','344.32','219.88',16,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Reflectect','rs','Gray',0,'RS','T3','Lightweight, Good All-Season Protection. Silver Urethane-Coated Polyester Fabric. Helps Keep the Vehicle Cooler. Water Resistant, Repels Dust and Dirt. Compact for Easy Trunk Storage. 3 Year Warranty.','3 Years','Outdoor/Indoor','reflectect.php','397.19','253.65',15,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Reflectect','rs','Gray',0,'RS','T4','Lightweight, Good All-Season Protection. Silver Urethane-Coated Polyester Fabric. Helps Keep the Vehicle Cooler. Water Resistant, Repels Dust and Dirt. Compact for Easy Trunk Storage. 3 Year Warranty.','3 Years','Outdoor/Indoor','reflectect.php','501.02','319.95',NULL,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Reflectect','rs','Gray',0,'RS','T5','Lightweight, Good All-Season Protection. Silver Urethane-Coated Polyester Fabric. Helps Keep the Vehicle Cooler. Water Resistant, Repels Dust and Dirt. Compact for Easy Trunk Storage. 3 Year Warranty.','3 Years','Outdoor/Indoor','reflectect.php','560.24','357.77',NULL,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Dustop','dust','Taupe',0,'TS','G1','Best Dust Protection Available! Soft 4-Layer Fabric Helps Prevent Dings and Stops All but the Finest Dust. Soft Inner Layer Protects Paint. Finest Indoor Protective Cover. 4 Year Warranty.','4 Years','Indoor','dustop.php','277.87','177.45',8,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Dustop','dust','Taupe',0,'TS','G2','Best Dust Protection Available! Soft 4-Layer Fabric Helps Prevent Dings and Stops All but the Finest Dust. Soft Inner Layer Protects Paint. Finest Indoor Protective Cover. 4 Year Warranty.','4 Years','Indoor','dustop.php','309.26','197.49',9,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Dustop','dust','Taupe',0,'TS','G3','Best Dust Protection Available! Soft 4-Layer Fabric Helps Prevent Dings and Stops All but the Finest Dust. Soft Inner Layer Protects Paint. Finest Indoor Protective Cover. 4 Year Warranty.','4 Years','Indoor','dustop.php','348.13','222.32',12,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Dustop','dust','Taupe',0,'TS','G4','Best Dust Protection Available! Soft 4-Layer Fabric Helps Prevent Dings and Stops All but the Finest Dust. Soft Inner Layer Protects Paint. Finest Indoor Protective Cover. 4 Year Warranty.','4 Years','Indoor','dustop.php','417.42','266.56',14,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Dustop','dust','Taupe',0,'TS','G5','Best Dust Protection Available! Soft 4-Layer Fabric Helps Prevent Dings and Stops All but the Finest Dust. Soft Inner Layer Protects Paint. Finest Indoor Protective Cover. 4 Year Warranty.','4 Years','Indoor','dustop.php','486.77','310.85',15,12,12,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Dustop','dust','Taupe',0,'TS','G6','Best Dust Protection Available! Soft 4-Layer Fabric Helps Prevent Dings and Stops All but the Finest Dust. Soft Inner Layer Protects Paint. Finest Indoor Protective Cover. 4 Year Warranty.','4 Years','Indoor','dustop.php','616.10','393.44',16,12,12,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Dustop','dust','Taupe',0,'TS','T0','Best Dust Protection Available! Soft 4-Layer Fabric Helps Prevent Dings and Stops All but the Finest Dust. Soft Inner Layer Protects Paint. Finest Indoor Protective Cover. 4 Year Warranty.','4 Years','Indoor','dustop.php','325.02','207.56',7,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Dustop','dust','Taupe',0,'TS','T1','Best Dust Protection Available! Soft 4-Layer Fabric Helps Prevent Dings and Stops All but the Finest Dust. Soft Inner Layer Protects Paint. Finest Indoor Protective Cover. 4 Year Warranty.','4 Years','Indoor','dustop.php','371.00','236.92',14,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Dustop','dust','Taupe',0,'TS','T2','Best Dust Protection Available! Soft 4-Layer Fabric Helps Prevent Dings and Stops All but the Finest Dust. Soft Inner Layer Protects Paint. Finest Indoor Protective Cover. 4 Year Warranty.','4 Years','Indoor','dustop.php','440.29','281.17',15,12,12,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Dustop','dust','Taupe',0,'TS','T3','Best Dust Protection Available! Soft 4-Layer Fabric Helps Prevent Dings and Stops All but the Finest Dust. Soft Inner Layer Protects Paint. Finest Indoor Protective Cover. 4 Year Warranty.','4 Years','Indoor','dustop.php','509.65','325.46',17,12,12,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Dustop','dust','Taupe',0,'TS','T4','Best Dust Protection Available! Soft 4-Layer Fabric Helps Prevent Dings and Stops All but the Finest Dust. Soft Inner Layer Protects Paint. Finest Indoor Protective Cover. 4 Year Warranty.','4 Years','Indoor','dustop.php','627.00','400.40',NULL,12,12,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Dustop','dust','Taupe',0,'TS','T5','Best Dust Protection Available! Soft 4-Layer Fabric Helps Prevent Dings and Stops All but the Finest Dust. Soft Inner Layer Protects Paint. Finest Indoor Protective Cover. 4 Year Warranty.','4 Years','Indoor','dustop.php','692.19','442.03',NULL,12,12,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Form-Fit','ff','Black.Charcoal Gray.Blue.Gray.Hunter Green.Red',1,'FB.FC.FD.FG.FN.FR','G1','Softest Cover Available! Body Hugging Polyester Knit. Spandex To Provide Stretch And Recovery. Finished On Inside w/100 percent Cotton Terry Loop Sheared To A Luxurious Soft Fleece Finish. 4 Year Warranty.','4 Years','Indoor','form-fit.php','461.74','300.59',9,9,9,24,0,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Form-Fit','ff','Black.Charcoal Gray.Blue.Gray.Hunter Green.Red',1,'FB.FC.FD.FG.FN.FR','G2','Softest Cover Available! Body Hugging Polyester Knit. Spandex To Provide Stretch And Recovery. Finished On Inside w/100 percent Cotton Terry Loop Sheared To A Luxurious Soft Fleece Finish. 4 Year Warranty.','4 Years','Indoor','form-fit.php','538.26','350.41',11,9,9,24,0,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Form-Fit','ff','Black.Charcoal Gray.Blue.Gray.Hunter Green.Red',1,'FB.FC.FD.FG.FN.FR','G3','Softest Cover Available! Body Hugging Polyester Knit. Spandex To Provide Stretch And Recovery. Finished On Inside w/100 percent Cotton Terry Loop Sheared To A Luxurious Soft Fleece Finish. 4 Year Warranty.','4 Years','Indoor','form-fit.php','604.74','393.69',11,9,9,24,0,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Form-Fit','ff','Black.Charcoal Gray.Blue.Gray.Hunter Green.Red',1,'FB.FC.FD.FG.FN.FR','G4','Softest Cover Available! Body Hugging Polyester Knit. Spandex To Provide Stretch And Recovery. Finished On Inside w/100 percent Cotton Terry Loop Sheared To A Luxurious Soft Fleece Finish. 4 Year Warranty.','4 Years','Indoor','form-fit.php','723.13','470.76',18,9,9,24,0,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Form-Fit','ff','Black.Charcoal Gray.Blue.Gray.Hunter Green.Red',1,'FB.FC.FD.FG.FN.FR','G5','Softest Cover Available! Body Hugging Polyester Knit. Spandex To Provide Stretch And Recovery. Finished On Inside w/100 percent Cotton Terry Loop Sheared To A Luxurious Soft Fleece Finish. 4 Year Warranty.','4 Years','Indoor','form-fit.php','868.69','565.52',18,12,12,24,0,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Form-Fit','ff','Black.Charcoal Gray.Blue.Gray.Hunter Green.Red',1,'FB.FC.FD.FG.FN.FR','G6','Softest Cover Available! Body Hugging Polyester Knit. Spandex To Provide Stretch And Recovery. Finished On Inside w/100 percent Cotton Terry Loop Sheared To A Luxurious Soft Fleece Finish. 4 Year Warranty.','4 Years','Indoor','form-fit.php','1033.37','672.72',20,12,12,24,0,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Form-Fit','ff','Black.Charcoal Gray.Blue.Gray.Hunter Green.Red',1,'FB.FC.FD.FG.FN.FR','T0','Softest Cover Available! Body Hugging Polyester Knit. Spandex To Provide Stretch And Recovery. Finished On Inside w/100 percent Cotton Terry Loop Sheared To A Luxurious Soft Fleece Finish. 4 Year Warranty.','4 Years','Indoor','form-fit.php','545.45','355.09',20,9,9,24,0,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Form-Fit','ff','Black.Charcoal Gray.Blue.Gray.Hunter Green.Red',1,'FB.FC.FD.FG.FN.FR','T1','Softest Cover Available! Body Hugging Polyester Knit. Spandex To Provide Stretch And Recovery. Finished On Inside w/100 percent Cotton Terry Loop Sheared To A Luxurious Soft Fleece Finish. 4 Year Warranty.','4 Years','Indoor','form-fit.php','639.53','416.34',20,9,9,24,0,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Form-Fit','ff','Black.Charcoal Gray.Blue.Gray.Hunter Green.Red',1,'FB.FC.FD.FG.FN.FR','T2','Softest Cover Available! Body Hugging Polyester Knit. Spandex To Provide Stretch And Recovery. Finished On Inside w/100 percent Cotton Terry Loop Sheared To A Luxurious Soft Fleece Finish. 4 Year Warranty.','4 Years','Indoor','form-fit.php','749.48','487.91',20,12,12,24,0,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Form-Fit','ff','Black.Charcoal Gray.Blue.Gray.Hunter Green.Red',1,'FB.FC.FD.FG.FN.FR','T3','Softest Cover Available! Body Hugging Polyester Knit. Spandex To Provide Stretch And Recovery. Finished On Inside w/100 percent Cotton Terry Loop Sheared To A Luxurious Soft Fleece Finish. 4 Year Warranty.','4 Years','Indoor','form-fit.php','887.02','577.45',22,12,12,24,0,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Form-Fit','ff','Black.Charcoal Gray.Blue.Gray.Hunter Green.Red',1,'FB.FC.FD.FG.FN.FR','T4','Softest Cover Available! Body Hugging Polyester Knit. Spandex To Provide Stretch And Recovery. Finished On Inside w/100 percent Cotton Terry Loop Sheared To A Luxurious Soft Fleece Finish. 4 Year Warranty.','4 Years','Indoor','form-fit.php','1055.60','687.19',NULL,12,12,24,0,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Form-Fit','ff','Black.Charcoal Gray.Blue.Gray.Hunter Green.Red',1,'FB.FC.FD.FG.FN.FR','T5','Softest Cover Available! Body Hugging Polyester Knit. Spandex To Provide Stretch And Recovery. Finished On Inside w/100 percent Cotton Terry Loop Sheared To A Luxurious Soft Fleece Finish. 4 Year Warranty.','4 Years','Indoor','form-fit.php','1178.03','766.90',NULL,12,12,24,0,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Ultratect','ut','Black.Gray.Blue.Tan',1,'UB.UG.UL.UT','G1','Made from a solution-dyed WeatherMax&reg;SL fabric. Fade Resistant / Water Resistant. Superior Shape Retention / Strong. Excellent UV Protection/Easy to Use/Easy to Clean. 4 Year Warranty.','4 Years','Outdoor/Indoor','ultratect.php','328.10','209.52',9,6.5,6.5,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Ultratect','ut','Black.Gray.Blue.Tan',1,'UB.UG.UL.UT','G2','Made from a solution-dyed WeatherMax&reg;SL fabric. Fade Resistant / Water Resistant. Superior Shape Retention / Strong. Excellent UV Protection/Easy to Use/Easy to Clean. 4 Year Warranty.','4 Years','Outdoor/Indoor','ultratect.php','361.63','230.94',10,6.5,6.5,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Ultratect','ut','Black.Gray.Blue.Tan',1,'UB.UG.UL.UT','G3','Made from a solution-dyed WeatherMax&reg;SL fabric. Fade Resistant / Water Resistant. Superior Shape Retention / Strong. Excellent UV Protection/Easy to Use/Easy to Clean. 4 Year Warranty.','4 Years','Outdoor/Indoor','ultratect.php','414.44','264.66',10,6.5,6.5,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Ultratect','ut','Black.Gray.Blue.Tan',1,'UB.UG.UL.UT','G4','Made from a solution-dyed WeatherMax&reg;SL fabric. Fade Resistant / Water Resistant. Superior Shape Retention / Strong. Excellent UV Protection/Easy to Use/Easy to Clean. 4 Year Warranty.','4 Years','Outdoor/Indoor','ultratect.php','495.79','316.61',15,6.5,6.5,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Ultratect','ut','Black.Gray.Blue.Tan',1,'UB.UG.UL.UT','G5','Made from a solution-dyed WeatherMax&reg;SL fabric. Fade Resistant / Water Resistant. Superior Shape Retention / Strong. Excellent UV Protection/Easy to Use/Easy to Clean. 4 Year Warranty.','4 Years','Outdoor/Indoor','ultratect.php','598.53','382.22',16,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Ultratect','ut','Black.Gray.Blue.Tan',1,'UB.UG.UL.UT','G6','Made from a solution-dyed WeatherMax&reg;SL fabric. Fade Resistant / Water Resistant. Superior Shape Retention / Strong. Excellent UV Protection/Easy to Use/Easy to Clean. 4 Year Warranty.','4 Years','Outdoor/Indoor','ultratect.php','704.23','449.72',18,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Ultratect','ut','Black.Gray.Blue.Tan',1,'UB.UG.UL.UT','T0','Made from a solution-dyed WeatherMax&reg;SL fabric. Fade Resistant / Water Resistant. Superior Shape Retention / Strong. Excellent UV Protection/Easy to Use/Easy to Clean. 4 Year Warranty.','4 Years','Outdoor/Indoor','ultratect.php','368.32','235.21',10,6.5,6.5,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Ultratect','ut','Black.Gray.Blue.Tan',1,'UB.UG.UL.UT','T1','Made from a solution-dyed WeatherMax&reg;SL fabric. Fade Resistant / Water Resistant. Superior Shape Retention / Strong. Excellent UV Protection/Easy to Use/Easy to Clean. 4 Year Warranty.','4 Years','Outdoor/Indoor','ultratect.php','440.08','281.04',20,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Ultratect','ut','Black.Gray.Blue.Tan',1,'UB.UG.UL.UT','T2','Made from a solution-dyed WeatherMax&reg;SL fabric. Fade Resistant / Water Resistant. Superior Shape Retention / Strong. Excellent UV Protection/Easy to Use/Easy to Clean. 4 Year Warranty.','4 Years','Outdoor/Indoor','ultratect.php','518.63','331.20',18,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Ultratect','ut','Black.Gray.Blue.Tan',1,'UB.UG.UL.UT','T3','Made from a solution-dyed WeatherMax&reg;SL fabric. Fade Resistant / Water Resistant. Superior Shape Retention / Strong. Excellent UV Protection/Easy to Use/Easy to Clean. 4 Year Warranty.','4 Years','Outdoor/Indoor','ultratect.php','623.89','398.41',22,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Ultratect','ut','Black.Gray.Blue.Tan',1,'UB.UG.UL.UT','T4','Made from a solution-dyed WeatherMax&reg;SL fabric. Fade Resistant / Water Resistant. Superior Shape Retention / Strong. Excellent UV Protection/Easy to Use/Easy to Clean. 4 Year Warranty.','4 Years','Outdoor/Indoor','ultratect.php','738.89','471.85',NULL,9,9,24,1,0);
INSERT INTO `cfccprices` (`name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES ('Ultratect','ut','Black.Gray.Blue.Tan',1,'UB.UG.UL.UT','T5','Made from a solution-dyed WeatherMax&reg;SL fabric. Fade Resistant / Water Resistant. Superior Shape Retention / Strong. Excellent UV Protection/Easy to Use/Easy to Clean. 4 Year Warranty.','4 Years','Outdoor/Indoor','ultratect.php','837.77','535.00',NULL,9,9,24,1,0);
/*!40000 ALTER TABLE `cfccprices` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2015-07-31 22:06:56
