-- MySQL dump 10.13  Distrib 5.5.35, for debian-linux-gnu (x86_64)
--
-- Host: localhost    Database: tjcars_production
-- ------------------------------------------------------
-- Server version	5.5.35-0ubuntu0.12.04.2

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `cfccprices`
--

DROP TABLE IF EXISTS `cfccprices`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `cfccprices` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `abrv` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `colors` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hasMultipleColors` tinyint(1) NOT NULL DEFAULT '0',
  `ext` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `size` enum('G1','G2','G3','G4','G5','G6','T0','T1','T2','T3','T4','T5') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `warranty` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `section` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `retail` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `jobber` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `weight` double DEFAULT NULL,
  `length` double DEFAULT NULL,
  `width` double DEFAULT NULL,
  `height` double DEFAULT NULL,
  `rushManufacture` tinyint(1) DEFAULT '1',
  `isMultiColor` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=91 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `cfccprices`
--

LOCK TABLES `cfccprices` WRITE;
/*!40000 ALTER TABLE `cfccprices` DISABLE KEYS */;
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (1,'Form-Fit','ff','Black.Bright Red.Charcoal Gray.Hunter Green.Metallic Dark Blue.Silver Gray',1,'FB.FC.FD.FG.FN.FR','G1','Softest Cover Available! Body Hugging Polyester Knit. Spandex To Provide Stretch And Recovery. Finished On Inside w/100 percent Cotton Terry Loop Sheared To A Luxurious Soft Fleece Finish. 4 Year Warranty.','4 Years','Indoor','form-fit.php','421.25','337.00',9,9,9,24,0,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (2,'Form-Fit','ff','Black.Bright Red.Charcoal Gray.Hunter Green.Metallic Dark Blue.Silver Gray',1,'FB.FC.FD.FG.FN.FR','G2','Softest Cover Available! Body Hugging Polyester Knit. Spandex To Provide Stretch And Recovery. Finished On Inside w/100 percent Cotton Terry Loop Sheared To A Luxurious Soft Fleece Finish. 4 Year Warranty.','4 Years','Indoor','form-fit.php','498.75','399.00',11,9,9,24,0,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (3,'Form-Fit','ff','Black.Bright Red.Charcoal Gray.Hunter Green.Metallic Dark Blue.Silver Gray',1,'FB.FC.FD.FG.FN.FR','G3','Softest Cover Available! Body Hugging Polyester Knit. Spandex To Provide Stretch And Recovery. Finished On Inside w/100 percent Cotton Terry Loop Sheared To A Luxurious Soft Fleece Finish. 4 Year Warranty.','4 Years','Indoor','form-fit.php','558.75','447.00',11,9,9,24,0,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (4,'Form-Fit','ff','Black.Bright Red.Charcoal Gray.Hunter Green.Metallic Dark Blue.Silver Gray',1,'FB.FC.FD.FG.FN.FR','G4','Softest Cover Available! Body Hugging Polyester Knit. Spandex To Provide Stretch And Recovery. Finished On Inside w/100 percent Cotton Terry Loop Sheared To A Luxurious Soft Fleece Finish. 4 Year Warranty.','4 Years','Indoor','form-fit.php','670.00','536.00',18,9,9,24,0,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (5,'Form-Fit','ff','Black.Bright Red.Charcoal Gray.Hunter Green.Metallic Dark Blue.Silver Gray',1,'FB.FC.FD.FG.FN.FR','G5','Softest Cover Available! Body Hugging Polyester Knit. Spandex To Provide Stretch And Recovery. Finished On Inside w/100 percent Cotton Terry Loop Sheared To A Luxurious Soft Fleece Finish. 4 Year Warranty.','4 Years','Indoor','form-fit.php','801.25','641.00',18,9,9,24,0,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (6,'Form-Fit','ff','Black.Bright Red.Charcoal Gray.Hunter Green.Metallic Dark Blue.Silver Gray',1,'FB.FC.FD.FG.FN.FR','T1','Softest Cover Available! Body Hugging Polyester Knit. Spandex To Provide Stretch And Recovery. Finished On Inside w/100 percent Cotton Terry Loop Sheared To A Luxurious Soft Fleece Finish. 4 Year Warranty.','4 Years','Indoor','form-fit.php','591.25','473.00',20,9,9,24,0,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (7,'Form-Fit','ff','Black.Bright Red.Charcoal Gray.Hunter Green.Metallic Dark Blue.Silver Gray',1,'FB.FC.FD.FG.FN.FR','T2','Softest Cover Available! Body Hugging Polyester Knit. Spandex To Provide Stretch And Recovery. Finished On Inside w/100 percent Cotton Terry Loop Sheared To A Luxurious Soft Fleece Finish. 4 Year Warranty.','4 Years','Indoor','form-fit.php','690.00','552.00',20,9,9,24,0,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (8,'Form-Fit','ff','Black.Bright Red.Charcoal Gray.Hunter Green.Metallic Dark Blue.Silver Gray',1,'FB.FC.FD.FG.FN.FR','T3','Softest Cover Available! Body Hugging Polyester Knit. Spandex To Provide Stretch And Recovery. Finished On Inside w/100 percent Cotton Terry Loop Sheared To A Luxurious Soft Fleece Finish. 4 Year Warranty.','4 Years','Indoor','form-fit.php','815.00','652.00',11,9,9,24,0,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (9,'Form-Fit','ff','Black.Bright Red.Charcoal Gray.Hunter Green.Metallic Dark Blue.Silver Gray',1,'FB.FC.FD.FG.FN.FR','T4','Softest Cover Available! Body Hugging Polyester Knit. Spandex To Provide Stretch And Recovery. Finished On Inside w/100 percent Cotton Terry Loop Sheared To A Luxurious Soft Fleece Finish. 4 Year Warranty.','4 Years','Indoor','form-fit.php','972.50','778.00',22,9,9,24,0,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (10,'Form-Fit','ff','Black.Bright Red.Charcoal Gray.Hunter Green.Metallic Dark Blue.Silver Gray',1,'FB.FC.FD.FG.FN.FR','T5','Softest Cover Available! Body Hugging Polyester Knit. Spandex To Provide Stretch And Recovery. Finished On Inside w/100 percent Cotton Terry Loop Sheared To A Luxurious Soft Fleece Finish. 4 Year Warranty.','4 Years','Indoor','form-fit.php','1083.75','867.00',24,9,9,24,0,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (11,'Polycotton','pd','Gray',0,'PD','G1','Durable polycotton blend that provides good basic protection that is resistant to tearing, punctures, rot and mildew. The polyester is resistant against sun and water, while the cotton gives a delicate touch to the finish. Comes with a 90-day warranty.','90 Days','Indoor','','191.25','153.00',6,7,7,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (12,'Polycotton','pd','Gray',0,'PD','G2','Durable polycotton blend that provides good basic protection that is resistant to tearing, punctures, rot and mildew. The polyester is resistant against sun and water, while the cotton gives a delicate touch to the finish. Comes with a 90-day warranty.','90 Days','Indoor','','223.75','179.00',7,7,7,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (13,'Polycotton','pd','Gray',0,'PD','G3','Durable polycotton blend that provides good basic protection that is resistant to tearing, punctures, rot and mildew. The polyester is resistant against sun and water, while the cotton gives a delicate touch to the finish. Comes with a 90-day warranty.','90 Days','Indoor','','256.25','205.00',7,7,7,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (14,'Polycotton','pd','Gray',0,'PD','G4','Durable polycotton blend that provides good basic protection that is resistant to tearing, punctures, rot and mildew. The polyester is resistant against sun and water, while the cotton gives a delicate touch to the finish. Comes with a 90-day warranty.','90 Days','Indoor','','308.75','247.00',11,7,7,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (15,'Polycotton','pd','Gray',0,'PD','G5','Durable polycotton blend that provides good basic protection that is resistant to tearing, punctures, rot and mildew. The polyester is resistant against sun and water, while the cotton gives a delicate touch to the finish. Comes with a 90-day warranty.','90 Days','Indoor','','348.75','279.00',11,9,9,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (16,'Polycotton','pd','Gray',0,'PD','T1','Durable polycotton blend that provides good basic protection that is resistant to tearing, punctures, rot and mildew. The polyester is resistant against sun and water, while the cotton gives a delicate touch to the finish. Comes with a 90-day warranty.','90 Days','Indoor','','276.25','221.00',11,7,7,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (17,'Polycotton','pd','Gray',0,'PD','T2','Durable polycotton blend that provides good basic protection that is resistant to tearing, punctures, rot and mildew. The polyester is resistant against sun and water, while the cotton gives a delicate touch to the finish. Comes with a 90-day warranty.','90 Days','Indoor','','328.75','263.00',11,9,9,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (18,'Polycotton','pd','Gray',0,'PD','T3','Durable polycotton blend that provides good basic protection that is resistant to tearing, punctures, rot and mildew. The polyester is resistant against sun and water, while the cotton gives a delicate touch to the finish. Comes with a 90-day warranty.','90 Days','Indoor','','361.25','289.00',13,9,9,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (19,'Polycotton','pd','Gray',0,'PD','T4','Durable polycotton blend that provides good basic protection that is resistant to tearing, punctures, rot and mildew. The polyester is resistant against sun and water, while the cotton gives a delicate touch to the finish. Comes with a 90-day warranty.','90 Days','Indoor','','447.50','358.00',13,9,9,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (20,'Polycotton','pd','Gray',0,'PD','T5','Durable polycotton blend that provides good basic protection that is resistant to tearing, punctures, rot and mildew. The polyester is resistant against sun and water, while the cotton gives a delicate touch to the finish. Comes with a 90-day warranty.','90 Days','Indoor','','498.75','399.00',15,9,9,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (21,'Reflectect','rs','Silver',0,'RS','G1','Lightweight, Good All-Season Protection. Silver Urethane-Coated Polyester Fabric. Helps Keep the Vehicle Cooler. Water Resistant, Repels Dust and Dirt. Compact for Easy Trunk Storage. 3 Year Warranty.','3 Years','Outdoor/Indoor','reflectect.php','227.50','182.00',6,7,7,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (22,'Reflectect','rs','Silver',0,'RS','G2','Lightweight, Good All-Season Protection. Silver Urethane-Coated Polyester Fabric. Helps Keep the Vehicle Cooler. Water Resistant, Repels Dust and Dirt. Compact for Easy Trunk Storage. 3 Year Warranty.','3 Years','Outdoor/Indoor','reflectect.php','262.50','210.00',7,7,7,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (23,'Reflectect','rs','Silver',0,'RS','G3','Lightweight, Good All-Season Protection. Silver Urethane-Coated Polyester Fabric. Helps Keep the Vehicle Cooler. Water Resistant, Repels Dust and Dirt. Compact for Easy Trunk Storage. 3 Year Warranty.','3 Years','Outdoor/Indoor','reflectect.php','290.00','232.00',7,7,7,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (24,'Reflectect','rs','Silver',0,'RS','G4','Lightweight, Good All-Season Protection. Silver Urethane-Coated Polyester Fabric. Helps Keep the Vehicle Cooler. Water Resistant, Repels Dust and Dirt. Compact for Easy Trunk Storage. 3 Year Warranty.','3 Years','Outdoor/Indoor','reflectect.php','338.75','271.00',11,7,7,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (25,'Reflectect','rs','Silver',0,'RS','G5','Lightweight, Good All-Season Protection. Silver Urethane-Coated Polyester Fabric. Helps Keep the Vehicle Cooler. Water Resistant, Repels Dust and Dirt. Compact for Easy Trunk Storage. 3 Year Warranty.','3 Years','Outdoor/Indoor','reflectect.php','393.75','315.00',11,9,9,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (26,'Reflectect','rs','Silver',0,'RS','T1','Lightweight, Good All-Season Protection. Silver Urethane-Coated Polyester Fabric. Helps Keep the Vehicle Cooler. Water Resistant, Repels Dust and Dirt. Compact for Easy Trunk Storage. 3 Year Warranty.','3 Years','Outdoor/Indoor','reflectect.php','303.75','243.00',11,7,7,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (27,'Reflectect','rs','Silver',0,'RS','T2','Lightweight, Good All-Season Protection. Silver Urethane-Coated Polyester Fabric. Helps Keep the Vehicle Cooler. Water Resistant, Repels Dust and Dirt. Compact for Easy Trunk Storage. 3 Year Warranty.','3 Years','Outdoor/Indoor','reflectect.php','352.50','282.00',11,9,9,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (28,'Reflectect','rs','Silver',0,'RS','T3','Lightweight, Good All-Season Protection. Silver Urethane-Coated Polyester Fabric. Helps Keep the Vehicle Cooler. Water Resistant, Repels Dust and Dirt. Compact for Easy Trunk Storage. 3 Year Warranty.','3 Years','Outdoor/Indoor','reflectect.php','407.50','326.00',15,9,9,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (29,'Reflectect','rs','Silver',0,'RS','T4','Lightweight, Good All-Season Protection. Silver Urethane-Coated Polyester Fabric. Helps Keep the Vehicle Cooler. Water Resistant, Repels Dust and Dirt. Compact for Easy Trunk Storage. 3 Year Warranty.','3 Years','Outdoor/Indoor','reflectect.php','510.00','408.00',13,9,9,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (30,'Reflectect','rs','Silver',0,'RS','T5','Lightweight, Good All-Season Protection. Silver Urethane-Coated Polyester Fabric. Helps Keep the Vehicle Cooler. Water Resistant, Repels Dust and Dirt. Compact for Easy Trunk Storage. 3 Year Warranty.','3 Years','Outdoor/Indoor','reflectect.php','565.00','452.00',15,9,9,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (31,'Sunbrella','sun','Pacific Blue.Gray.Toast',1,'D1.D4.D6','G1','Durable Long-Lasting Fabric. Best For Intense Sun Locations. Solution Dyed Woven Acrylic. Provides Almost Complete UV Block, protecting Interior and Exterior Finish. 5 Year Warranty.','6 Years','Outdoor/Indoor','sunbrella.php','553.75','443.00',10,9,9,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (32,'Sunbrella','sun','Pacific Blue.Gray.Toast',1,'D1.D4.D6','G2','Durable Long-Lasting Fabric. Best For Intense Sun Locations. Solution Dyed Woven Acrylic. Provides Almost Complete UV Block, protecting Interior and Exterior Finish. 5 Year Warranty.','6 Years','Outdoor/Indoor','sunbrella.php','621.25','497.00',12,9,9,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (33,'Sunbrella','sun','Pacific Blue.Gray.Toast',1,'D1.D4.D6','G3','Durable Long-Lasting Fabric. Best For Intense Sun Locations. Solution Dyed Woven Acrylic. Provides Almost Complete UV Block, protecting Interior and Exterior Finish. 5 Year Warranty.','6 Years','Outdoor/Indoor','sunbrella.php','696.25','557.00',12,9,9,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (34,'Sunbrella','sun','Pacific Blue.Gray.Toast',1,'D1.D4.D6','G4','Durable Long-Lasting Fabric. Best For Intense Sun Locations. Solution Dyed Woven Acrylic. Provides Almost Complete UV Block, protecting Interior and Exterior Finish. 5 Year Warranty.','6 Years','Outdoor/Indoor','sunbrella.php','778.75','623.00',18,9,9,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (35,'Sunbrella','sun','Pacific Blue.Gray.Toast',1,'D1.D4.D6','G5','Durable Long-Lasting Fabric. Best For Intense Sun Locations. Solution Dyed Woven Acrylic. Provides Almost Complete UV Block, protecting Interior and Exterior Finish. 5 Year Warranty.','6 Years','Outdoor/Indoor','sunbrella.php','948.75','759.00',18,12,12,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (36,'Sunbrella','sun','Pacific Blue.Gray.Toast',1,'D1.D4.D6','T1','Durable Long-Lasting Fabric. Best For Intense Sun Locations. Solution Dyed Woven Acrylic. Provides Almost Complete UV Block, protecting Interior and Exterior Finish. 5 Year Warranty.','6 Years','Outdoor/Indoor','sunbrella.php','710.00','568.00',18,9,9,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (37,'Sunbrella','sun','Pacific Blue.Gray.Toast',1,'D1.D4.D6','T2','Durable Long-Lasting Fabric. Best For Intense Sun Locations. Solution Dyed Woven Acrylic. Provides Almost Complete UV Block, protecting Interior and Exterior Finish. 5 Year Warranty.','6 Years','Outdoor/Indoor','sunbrella.php','792.50','634.00',18,12,12,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (38,'Sunbrella','sun','Pacific Blue.Gray.Toast',1,'D1.D4.D6','T3','Durable Long-Lasting Fabric. Best For Intense Sun Locations. Solution Dyed Woven Acrylic. Provides Almost Complete UV Block, protecting Interior and Exterior Finish. 5 Year Warranty.','6 Years','Outdoor/Indoor','sunbrella.php','970.00','776.00',22,12,12,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (39,'Sunbrella','sun','Pacific Blue.Gray.Toast',1,'D1.D4.D6','T4','Durable Long-Lasting Fabric. Best For Intense Sun Locations. Solution Dyed Woven Acrylic. Provides Almost Complete UV Block, protecting Interior and Exterior Finish. 5 Year Warranty.','6 Years','Outdoor/Indoor','sunbrella.php','1215.00','972.00',20,12,12,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (40,'Sunbrella','sun','Pacific Blue.Gray.Toast',1,'D1.D4.D6','T5','Durable Long-Lasting Fabric. Best For Intense Sun Locations. Solution Dyed Woven Acrylic. Provides Almost Complete UV Block, protecting Interior and Exterior Finish. 5 Year Warranty.','6 Years','Outdoor/Indoor','sunbrella.php','1317.50','1054.00',22,12,12,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (41,'Tan Flannel','tf','Tan',0,'TF','G1','Flannel provides a soft delicate touch to keep finishes in good condition. Intended for indoor storage it is made of a durable polycotton blend with a napped underside finish. Comes with a 90-day warranty.','90 Days','Indoor','','342.50','274.00',9,7,7,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (42,'Tan Flannel','tf','Tan',0,'TF','G2','Flannel provides a soft delicate touch to keep finishes in good condition. Intended for indoor storage it is made of a durable polycotton blend with a napped underside finish. Comes with a 90-day warranty.','90 Days','Indoor','','381.25','305.00',11,9,9,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (43,'Tan Flannel','tf','Tan',0,'TF','G3','Flannel provides a soft delicate touch to keep finishes in good condition. Intended for indoor storage it is made of a durable polycotton blend with a napped underside finish. Comes with a 90-day warranty.','90 Days','Indoor','','427.50','342.00',11,9,9,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (44,'Tan Flannel','tf','Tan',0,'TF','G4','Flannel provides a soft delicate touch to keep finishes in good condition. Intended for indoor storage it is made of a durable polycotton blend with a napped underside finish. Comes with a 90-day warranty.','90 Days','Indoor','','526.25','421.00',18,9,9,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (45,'Tan Flannel','tf','Tan',0,'TF','G5','Flannel provides a soft delicate touch to keep finishes in good condition. Intended for indoor storage it is made of a durable polycotton blend with a napped underside finish. Comes with a 90-day warranty.','90 Days','Indoor','','598.75','479.00',18,9,9,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (46,'Tan Flannel','tf','Tan',0,'TF','T1','Flannel provides a soft delicate touch to keep finishes in good condition. Intended for indoor storage it is made of a durable polycotton blend with a napped underside finish. Comes with a 90-day warranty.','90 Days','Indoor','','447.50','358.00',18,9,9,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (47,'Tan Flannel','tf','Tan',0,'TF','T2','Flannel provides a soft delicate touch to keep finishes in good condition. Intended for indoor storage it is made of a durable polycotton blend with a napped underside finish. Comes with a 90-day warranty.','90 Days','Indoor','','538.75','431.00',18,9,9,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (48,'Tan Flannel','tf','Tan',0,'TF','T3','Flannel provides a soft delicate touch to keep finishes in good condition. Intended for indoor storage it is made of a durable polycotton blend with a napped underside finish. Comes with a 90-day warranty.','90 Days','Indoor','','617.50','494.00',20,9,9,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (49,'Tan Flannel','tf','Tan',0,'TF','T4','Flannel provides a soft delicate touch to keep finishes in good condition. Intended for indoor storage it is made of a durable polycotton blend with a napped underside finish. Comes with a 90-day warranty.','90 Days','Indoor','','768.75','615.00',20,9,9,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (50,'Tan Flannel','tf','Tan',0,'TF','T5','Flannel provides a soft delicate touch to keep finishes in good condition. Intended for indoor storage it is made of a durable polycotton blend with a napped underside finish. Comes with a 90-day warranty.','90 Days','Indoor','','853.75','683.00',22,9,9,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (51,'Ultratect','ut','Black.Gray.Blue.Tan',1,'UB.UG.UL.UT','G1','Made from a solution-dyed WeatherMax&reg;SL fabric. Fade Resistant / Water Resistant. Superior Shape Retention / Strong. Excellent UV Protection/Easy to Use/Easy to Clean. 4 Year Warranty.','5 Years','Outdoor/Indoor','ultratect.php','322.50','258.00',9,7,7,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (52,'Ultratect','ut','Black.Gray.Blue.Tan',1,'UB.UG.UL.UT','G2','Made from a solution-dyed WeatherMax&reg;SL fabric. Fade Resistant / Water Resistant. Superior Shape Retention / Strong. Excellent UV Protection/Easy to Use/Easy to Clean. 4 Year Warranty.','5 Years','Outdoor/Indoor','ultratect.php','348.75','279.00',10,7,7,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (53,'Ultratect','ut','Black.Gray.Blue.Tan',1,'UB.UG.UL.UT','G3','Made from a solution-dyed WeatherMax&reg;SL fabric. Fade Resistant / Water Resistant. Superior Shape Retention / Strong. Excellent UV Protection/Easy to Use/Easy to Clean. 4 Year Warranty.','5 Years','Outdoor/Indoor','ultratect.php','402.50','322.00',10,7,7,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (54,'Ultratect','ut','Black.Gray.Blue.Tan',1,'UB.UG.UL.UT','G4','Made from a solution-dyed WeatherMax&reg;SL fabric. Fade Resistant / Water Resistant. Superior Shape Retention / Strong. Excellent UV Protection/Easy to Use/Easy to Clean. 4 Year Warranty.','5 Years','Outdoor/Indoor','ultratect.php','476.25','381.00',15,7,7,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (55,'Ultratect','ut','Black.Gray.Blue.Tan',1,'UB.UG.UL.UT','G5','Made from a solution-dyed WeatherMax&reg;SL fabric. Fade Resistant / Water Resistant. Superior Shape Retention / Strong. Excellent UV Protection/Easy to Use/Easy to Clean. 4 Year Warranty.','5 Years','Outdoor/Indoor','ultratect.php','570.00','456.00',16,9,9,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (56,'Ultratect','ut','Black.Gray.Blue.Tan',1,'UB.UG.UL.UT','T1','Made from a solution-dyed WeatherMax&reg;SL fabric. Fade Resistant / Water Resistant. Superior Shape Retention / Strong. Excellent UV Protection/Easy to Use/Easy to Clean. 4 Year Warranty.','5 Years','Outdoor/Indoor','ultratect.php','422.50','338.00',20,9,9,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (57,'Ultratect','ut','Black.Gray.Blue.Tan',1,'UB.UG.UL.UT','T2','Made from a solution-dyed WeatherMax&reg;SL fabric. Fade Resistant / Water Resistant. Superior Shape Retention / Strong. Excellent UV Protection/Easy to Use/Easy to Clean. 4 Year Warranty.','5 Years','Outdoor/Indoor','ultratect.php','496.25','397.00',18,9,9,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (58,'Ultratect','ut','Black.Gray.Blue.Tan',1,'UB.UG.UL.UT','T3','Made from a solution-dyed WeatherMax&reg;SL fabric. Fade Resistant / Water Resistant. Superior Shape Retention / Strong. Excellent UV Protection/Easy to Use/Easy to Clean. 4 Year Warranty.','5 Years','Outdoor/Indoor','ultratect.php','596.25','477.00',22,9,9,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (59,'Ultratect','ut','Black.Gray.Blue.Tan',1,'UB.UG.UL.UT','T4','Made from a solution-dyed WeatherMax&reg;SL fabric. Fade Resistant / Water Resistant. Superior Shape Retention / Strong. Excellent UV Protection/Easy to Use/Easy to Clean. 4 Year Warranty.','5 Years','Outdoor/Indoor','ultratect.php','703.75','563.00',15,9,9,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (60,'Ultratect','ut','Black.Gray.Blue.Tan',1,'UB.UG.UL.UT','T5','Made from a solution-dyed WeatherMax&reg;SL fabric. Fade Resistant / Water Resistant. Superior Shape Retention / Strong. Excellent UV Protection/Easy to Use/Easy to Clean. 4 Year Warranty.','5 Years','Outdoor/Indoor','ultratect.php','797.50','638.00',17,9,9,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (61,'ViewShield','vs','Clear',0,'VS','G1','ViewShield is a translucent nylon material that protects your vehicles from dust while still allowing the paint and contours to show through. Lightweight with overlapped double-needle stitched seams. Comes with a 4-year warranty.','4 Years','Indoor','','375.00','300.00',2,7,7,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (62,'ViewShield','vs','Clear',0,'VS','G2','ViewShield is a translucent nylon material that protects your vehicles from dust while still allowing the paint and contours to show through. Lightweight with overlapped double-needle stitched seams. Comes with a 4-year warranty.','4 Years','Indoor','','421.25','337.00',3,7,7,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (63,'ViewShield','vs','Clear',0,'VS','G3','ViewShield is a translucent nylon material that protects your vehicles from dust while still allowing the paint and contours to show through. Lightweight with overlapped double-needle stitched seams. Comes with a 4-year warranty.','4 Years','Indoor','','492.50','394.00',3,7,7,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (64,'ViewShield','vs','Clear',0,'VS','G4','ViewShield is a translucent nylon material that protects your vehicles from dust while still allowing the paint and contours to show through. Lightweight with overlapped double-needle stitched seams. Comes with a 4-year warranty.','4 Years','Indoor','','578.75','463.00',4,7,7,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (65,'ViewShield','vs','Clear',0,'VS','G5','ViewShield is a translucent nylon material that protects your vehicles from dust while still allowing the paint and contours to show through. Lightweight with overlapped double-needle stitched seams. Comes with a 4-year warranty.','4 Years','Indoor','','677.50','542.00',4,7,7,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (66,'ViewShield','vs','Clear',0,'VS','T1','ViewShield is a translucent nylon material that protects your vehicles from dust while still allowing the paint and contours to show through. Lightweight with overlapped double-needle stitched seams. Comes with a 4-year warranty.','4 Years','Indoor','','506.25','405.00',6,7,7,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (67,'ViewShield','vs','Clear',0,'VS','T2','ViewShield is a translucent nylon material that protects your vehicles from dust while still allowing the paint and contours to show through. Lightweight with overlapped double-needle stitched seams. Comes with a 4-year warranty.','4 Years','Indoor','','598.75','479.00',6,7,7,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (68,'ViewShield','vs','Clear',0,'VS','T3','ViewShield is a translucent nylon material that protects your vehicles from dust while still allowing the paint and contours to show through. Lightweight with overlapped double-needle stitched seams. Comes with a 4-year warranty.','4 Years','Indoor','','696.25','557.00',7,7,7,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (69,'ViewShield','vs','Clear',0,'VS','T4','ViewShield is a translucent nylon material that protects your vehicles from dust while still allowing the paint and contours to show through. Lightweight with overlapped double-needle stitched seams. Comes with a 4-year warranty.','4 Years','Indoor','','853.75','683.00',7,7,7,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (70,'ViewShield','vs','Clear',0,'VS','T5','ViewShield is a translucent nylon material that protects your vehicles from dust while still allowing the paint and contours to show through. Lightweight with overlapped double-needle stitched seams. Comes with a 4-year warranty.','4 Years','Indoor','','952.50','762.00',8,9,9,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (71,'WeatherShield HD','wsHD','Gray',0,'HG','G1','&quot;Outsmart the Outdoors&quot; with this Heavy-Duty Version of Weathershield with Nextec&reg; Barrier Finish by Epic. Weathershield HD Sheds Water, Blocks Dust/Dirt, & Still Breathes! Solution Dyed Fibers Resist Fade. 5 Year Warranty.','6 Years','Outdoor/Indoor','weathershieldHD.php','582.50','466.00',10,7,7,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (72,'WeatherShield HD','wsHD','Gray',0,'HG','G2','&quot;Outsmart the Outdoors&quot; with this Heavy-Duty Version of Weathershield with Nextec&reg; Barrier Finish by Epic. Weathershield HD Sheds Water, Blocks Dust/Dirt, & Still Breathes! Solution Dyed Fibers Resist Fade. 5 Year Warranty.','6 Years','Outdoor/Indoor','weathershieldHD.php','656.25','525.00',12,7,7,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (73,'WeatherShield HD','wsHD','Gray',0,'HG','G3','&quot;Outsmart the Outdoors&quot; with this Heavy-Duty Version of Weathershield with Nextec&reg; Barrier Finish by Epic. Weathershield HD Sheds Water, Blocks Dust/Dirt, & Still Breathes! Solution Dyed Fibers Resist Fade. 5 Year Warranty.','6 Years','Outdoor/Indoor','weathershieldHD.php','731.25','585.00',14,9,9,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (74,'WeatherShield HD','wsHD','Gray',0,'HG','G4','&quot;Outsmart the Outdoors&quot; with this Heavy-Duty Version of Weathershield with Nextec&reg; Barrier Finish by Epic. Weathershield HD Sheds Water, Blocks Dust/Dirt, & Still Breathes! Solution Dyed Fibers Resist Fade. 5 Year Warranty.','6 Years','Outdoor/Indoor','weathershieldHD.php','838.75','671.00',18,9,9,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (75,'WeatherShield HD','wsHD','Gray',0,'HG','G5','&quot;Outsmart the Outdoors&quot; with this Heavy-Duty Version of Weathershield with Nextec&reg; Barrier Finish by Epic. Weathershield HD Sheds Water, Blocks Dust/Dirt, & Still Breathes! Solution Dyed Fibers Resist Fade. 5 Year Warranty.','6 Years','Outdoor/Indoor','weathershieldHD.php','993.75','795.00',18,9,9,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (76,'WeatherShield HD','wsHD','Gray',0,'HG','T1','&quot;Outsmart the Outdoors&quot; with this Heavy-Duty Version of Weathershield with Nextec&reg; Barrier Finish by Epic. Weathershield HD Sheds Water, Blocks Dust/Dirt, & Still Breathes! Solution Dyed Fibers Resist Fade. 5 Year Warranty.','6 Years','Outdoor/Indoor','weathershieldHD.php','751.25','601.00',18,9,9,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (77,'WeatherShield HD','wsHD','Gray',0,'HG','T2','&quot;Outsmart the Outdoors&quot; with this Heavy-Duty Version of Weathershield with Nextec&reg; Barrier Finish by Epic. Weathershield HD Sheds Water, Blocks Dust/Dirt, & Still Breathes! Solution Dyed Fibers Resist Fade. 5 Year Warranty.','6 Years','Outdoor/Indoor','weathershieldHD.php','852.50','682.00',18,9,9,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (78,'WeatherShield HD','wsHD','Gray',0,'HG','T3','&quot;Outsmart the Outdoors&quot; with this Heavy-Duty Version of Weathershield with Nextec&reg; Barrier Finish by Epic. Weathershield HD Sheds Water, Blocks Dust/Dirt, & Still Breathes! Solution Dyed Fibers Resist Fade. 5 Year Warranty.','6 Years','Outdoor/Indoor','weathershieldHD.php','1015.00','812.00',22,12,12,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (79,'WeatherShield HD','wsHD','Gray',0,'HG','T4','&quot;Outsmart the Outdoors&quot; with this Heavy-Duty Version of Weathershield with Nextec&reg; Barrier Finish by Epic. Weathershield HD Sheds Water, Blocks Dust/Dirt, & Still Breathes! Solution Dyed Fibers Resist Fade. 5 Year Warranty.','6 Years','Outdoor/Indoor','weathershieldHD.php','1257.50','1006.00',20,12,12,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (80,'WeatherShield HD','wsHD','Gray',0,'HG','T5','&quot;Outsmart the Outdoors&quot; with this Heavy-Duty Version of Weathershield with Nextec&reg; Barrier Finish by Epic. Weathershield HD Sheds Water, Blocks Dust/Dirt, & Still Breathes! Solution Dyed Fibers Resist Fade. 5 Year Warranty.','6 Years','Outdoor/Indoor','weathershieldHD.php','1366.25','1093.00',22,12,12,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (81,'WeatherShield HP','wsHP','Bright Blue.Black.Gray.Red.Taupe.Multi-color',1,'PA.PB.PG.PR.PT.PX','G1','Ultimate all-weather fabric. Dramatic Rain Dispersion / Superior Dry Time & Breathablility. Solution-dyed fibers are UV & Fade Resistant. Light-Weight/Packs Small / Easy Care. 4 Year Warranty.','4 Years','Outdoor/Indoor','weathershield.php','437.50','350.00',8,7,7,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (82,'WeatherShield HP','wsHP','Bright Blue.Black.Gray.Red.Taupe.Multi-color',1,'PA.PB.PG.PR.PT.PX','G2','Ultimate all-weather fabric. Dramatic Rain Dispersion / Superior Dry Time & Breathablility. Solution-dyed fibers are UV & Fade Resistant. Light-Weight/Packs Small / Easy Care. 4 Year Warranty.','4 Years','Outdoor/Indoor','weathershield.php','498.75','399.00',9,7,7,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (83,'WeatherShield HP','wsHP','Bright Blue.Black.Gray.Red.Taupe.Multi-color',1,'PA.PB.PG.PR.PT.PX','G3','Ultimate all-weather fabric. Dramatic Rain Dispersion / Superior Dry Time & Breathablility. Solution-dyed fibers are UV & Fade Resistant. Light-Weight/Packs Small / Easy Care. 4 Year Warranty.','4 Years','Outdoor/Indoor','weathershield.php','567.50','454.00',9,7,7,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (84,'WeatherShield HP','wsHP','Bright Blue.Black.Gray.Red.Taupe.Multi-color',1,'PA.PB.PG.PR.PT.PX','G4','Ultimate all-weather fabric. Dramatic Rain Dispersion / Superior Dry Time & Breathablility. Solution-dyed fibers are UV & Fade Resistant. Light-Weight/Packs Small / Easy Care. 4 Year Warranty.','4 Years','Outdoor/Indoor','weathershield.php','690.00','552.00',14,7,7,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (85,'WeatherShield HP','wsHP','Bright Blue.Black.Gray.Red.Taupe.Multi-color',1,'PA.PB.PG.PR.PT.PX','G5','Ultimate all-weather fabric. Dramatic Rain Dispersion / Superior Dry Time & Breathablility. Solution-dyed fibers are UV & Fade Resistant. Light-Weight/Packs Small / Easy Care. 4 Year Warranty.','4 Years','Outdoor/Indoor','weathershield.php','820.00','656.00',14,9,9,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (86,'WeatherShield HP','wsHP','Bright Blue.Black.Gray.Red.Taupe.Multi-color',1,'PA.PB.PG.PR.PT.PX','T1','Ultimate all-weather fabric. Dramatic Rain Dispersion / Superior Dry Time & Breathablility. Solution-dyed fibers are UV & Fade Resistant. Light-Weight/Packs Small / Easy Care. 4 Year Warranty.','4 Years','Outdoor/Indoor','weathershield.php','607.50','486.00',14,7,7,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (87,'WeatherShield HP','wsHP','Bright Blue.Black.Gray.Red.Taupe.Multi-color',1,'PA.PB.PG.PR.PT.PX','T2','Ultimate all-weather fabric. Dramatic Rain Dispersion / Superior Dry Time & Breathablility. Solution-dyed fibers are UV & Fade Resistant. Light-Weight/Packs Small / Easy Care. 4 Year Warranty.','4 Years','Outdoor/Indoor','weathershield.php','717.50','574.00',16,9,9,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (88,'WeatherShield HP','wsHP','Bright Blue.Black.Gray.Red.Taupe.Multi-color',1,'PA.PB.PG.PR.PT.PX','T3','Ultimate all-weather fabric. Dramatic Rain Dispersion / Superior Dry Time & Breathablility. Solution-dyed fibers are UV & Fade Resistant. Light-Weight/Packs Small / Easy Care. 4 Year Warranty.','4 Years','Outdoor/Indoor','weathershield.php','846.25','677.00',15,9,9,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (89,'WeatherShield HP','wsHP','Bright Blue.Black.Gray.Red.Taupe.Multi-color',1,'PA.PB.PG.PR.PT.PX','T4','Ultimate all-weather fabric. Dramatic Rain Dispersion / Superior Dry Time & Breathablility. Solution-dyed fibers are UV & Fade Resistant. Light-Weight/Packs Small / Easy Care. 4 Year Warranty.','4 Years','Outdoor/Indoor','weathershield.php','1037.50','830.00',18,9,9,24,1,0);
INSERT INTO `cfccprices` (`id`, `name`, `abrv`, `colors`, `hasMultipleColors`, `ext`, `size`, `description`, `warranty`, `type`, `section`, `retail`, `jobber`, `weight`, `length`, `width`, `height`, `rushManufacture`, `isMultiColor`) VALUES (90,'WeatherShield HP','wsHP','Bright Blue.Black.Gray.Red.Taupe.Multi-color',1,'PA.PB.PG.PR.PT.PX','T5','Ultimate all-weather fabric. Dramatic Rain Dispersion / Superior Dry Time & Breathablility. Solution-dyed fibers are UV & Fade Resistant. Light-Weight/Packs Small / Easy Care. 4 Year Warranty.','4 Years','Outdoor/Indoor','weathershield.php','1161.25','929.00',20,9,9,24,1,0);
/*!40000 ALTER TABLE `cfccprices` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2024-08-27 23:14:11
